project:
  type: website
  output-dir: docs

website:
  favicon: pics/icon.jpg
  navbar:
    title: false
    logo: pics/icon.jpg
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: publications
    tools: 
      - icon: github
        menu: 
          - text: Source Code
            url: https://github.com/rkbrugger/rkbrugger.github.io
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Rahel K. Brügger"
    right: |
      Made with {{< fa solid heart >}}, [{{< fa brands r-project >}}](https://www.r-project.org/) and [Quarto](https://quarto.org/) <br/>
      Background Illustration from [absurd.design](https://absurd.design/), other illustrations by [blush](https://blush.design/collections/open-peeps/open-peeps)
format:
  html:
    theme: 
      - minty
      - styles.scss
    css: styles.css
    toc: true

editor: visual

